name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

permissions:
  pages: write  # Grants only GitHub Pages deployment permission
  id-token: write  # Required for authentication

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest version

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Latest version

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Updated to v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
