name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

permissions:
  pages: write  # Only gives permission for GitHub Pages
  id-token: write  # Required for authentication

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files  # This ensures your HTML, CSS, and JS are deployed
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Deploy everything in the repository root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

